n = '\u001b[30;1m'                                        
r = '\u001b[31;1m'                                         
v = '\u001b[32;1m'
a = '\u001b[33;1m'
az = '\u001b[34;1m'
ro= '\u001b[35;1m'
c= '\u001b[36;1m'
b= '\u001b[37;1m'
Reset = '\u001b[0m'
def uso_Fotosploit():
      print(ro+"> "+a+"Guia "+b)
      print("")
      print("A primera Vista aparecera una calavera gigante,para comenzar a utilizar ")
      print("esta herramienta pondremos:                         ")
      print("$ "+v+"show options "+b)
      print("")
      print(ro+"> "+a+" opciones "+b)
      print("")
      print(ro+"> "+a+"set foto"+b+" "+r+"= "+b+"esta opcion permitira agregar un foto,en las predeterminadas")
      print("estan ["+c+"youtube"+b+"] ["+c+"PUBG"+b+"] ["+c+"Free Fire"+b+"] ["+c+"Anime"+b+"] ["+c+"pornografia"+b+"]  ["+c+"Bokep"+b+"]")
      print("["+c+"facebook"+b+"] "+b+"para agregar una de estas imagenes predeterminadas tienes que ")                                                                              
      print("poner:"+b+"                                   "+b)
      print("$ "+v+"set foto"+b+" PUBG o cualquier imagen           ")                                                                                                                                                                                     
      print("ahora para agregar una imagen personalizada debes saber la ruta de la")
      print("imagen.jpg y agregarla ala opcion set foto ejemplo:")
      print("$ "+v+"set foto "+b+"/sdcard/Download/imagen.jpg")
      print("si te da problemas con las fotos prueba renombrando la foto a .jpg")
      print("")
      print(ro+"> "+a+"set tilte url "+r+"="+b+" esta opcion permitira agregar un titulo al phising")   
      print("para agregarlo solo vasta con poner set title url y el titulo que")
      print("quieras")
      print("")
      print(ro+"> "+a+"set view "+r+"="+b+" esto sera la vista de la persona,aqui podras poner"+c)
      print("youtube "+b+"o "+b+"["+c+"facebook"+b+"]  ejemplo :")
      print("$ "+v+"set view "+b+"facebook")
      print("")
      print(ro+"> "+a+"Go "+r+"= "+b+"esta opcion GO es para que comienze el scrip")
      print("")
      print("Una vez que comienze te va a dar links, Tendras que copiar")
      print("el link que tiene como nombre "+v+".ngrok "+b+"este podras mandar por")
      print("whatsapp ala victima una vez que la victima ingrese tus datos")
      print("el programa dirá los datos que puso,y asi se obtiene las credenciales,")
      print("hay gente que se les ase sospechoso el link nrgok puedes buscar en")
      print("google acortadores de urls para que sea menos sospechosos.")
      print(Reset)
    
def uso_Facebook_brute():
      print(ro+"> "+a+"Guia "+b+"                                                    ")
      print("")
      print("Para utilizar esta herramienta debes ingresar el ID de la victima ")
      print("pero como saber el ID de la victima?, es facil entra al           ")
      print("perfil de esa persona y copia el url en la parte de arriba        ")
      print("despues copia este link : "+v+"https://es.piliapp.com/facebook/id/   "+b+"  ")
      print("este link que llevara a una pagina donde podras pegar la url de   ")
      print("la victima despues de pegar el ID le daras a Generar User ID      ")
      print("cuando ya tengas la ID ahora la pondras en la herramienta facebook")
      print("_brute                                                            ")
      print("")
      print(ro+"> "+a+"CREAR UN DICCIONARIO "+b+"                                    ")
      print("")
      print("los diccionarios es un texto donde se almacenaran posibles claves ")
      print("de ingreso al face lo mas apropiado es aserlas tu mismo y como    ")
      print("las ago?                                                          ")
      print("buena hay 2 formas,crearlas tu mismo o instalar una herramienta   ")
      print("para que genere tipos de claves,hay una herramienta en general    ")
      print("llama cupp para instalarla tendras que volver al menu          ")
      print("principal y ir al numero 2 despues ir a donde dice diccionario    ")
      print("ai abra una guia para crear un diccionario con la herramienta     ")
      print("cupp                                                              "+Reset) 
      print("")
def uso_cupp():
      print(ro+"> "+a+"Guia")
      print("")
      print(b+"para utilizar esta herramienta y crear un diccionario,y una vez estes")
      print("en la herramienta te pedira los siguientes datos:")
      print("")
      print(c+"[OJO si no sabes alguno de los datos puedes saltar dando enter]"+b)
      print("")
      print("["+ro+"> "+a+"First Name "+b+"] = aqui pondras el primer nombre de la victima")
      print("")
      print(b+"["+ro+"> "+a+"Surname"+b+"] = aqui pondras el apellido")
      print("")
      print("[ "+ro+"> "+a+"Nickname"+b+"] = aqui irá algun apodo de la victima")
      print("")
      print("[ "+ro+"> "+a+"Birthdate"+b+"] = aqui pondras el dia/mes/año  del cumpleaños de la")
      print("victima ejemplo:  04111996")
      print("")
      print("[ "+ro+"> "+a+"(Partners) name"+b+"] = Nombre del padre de la victima")
      print("")
      print("[ "+ro+"> "+a+"(Partners) Nickname"+b+"] = algun apodo del padre")
      print("")
      print("[ "+ro+"> "+a+"(Partners) Birthdate"+b+"] = e igual forma el dia/mes/año del cumpleaños")
      print("")
      print("[ "+ro+"> "+a+"Child's name"+b+"] = Nombre del hijo si tiene")
      print("")
      print("[ "+ro+"> "+a+"Child's nickname"+b+"] = apodo del niño")
      print("")
      print("[ "+ro+"> "+a+"Child's birthdate"+b+"] = cumpleaños del niño")
      print("")
      print("[ "+ro+"> "+a+"Pet's name"+b+"] = nombre de la mascota")
      print("")
      print("[ "+ro+"> "+a+"Company name"+b+"] = nombre de la empresa")
      print("")
      print("Ahora te aparecera estas letra")
      print("")
      print("["+ro+"> "+a+"Do you want to add some key words about the victima? "+ro+"Y/[N]] = "+b+"aqui te")
      print("esta diciendo si quieres implementar mas datos o palabras claves")
      print("["+c+"ojo cada palabra tiene que estar separado por comas"+b+"]")
      print("[Y] "+ro+"= "+b+"para si")
      print("[N] "+ro+"= "+b+"pano no")
      print("")
      print("ahora te aparecera los siguiente")
      print("")
      print("["+ro+"> "+a+"Do you want to add special chars at the end of words Y/[N]] "+b+"= aqui dice")
      print("que si quieres poner caracteres espaciales como : $ € $ , esos tipos")
      print("de signos")
      print("de igual forma Y = si N = no")
      print("")
      print("siguiente:")
      print("")
      print("[ "+ro+"> "+a+"Do you want to add some random numbers at the end of words Y/[N]] "+b+"=")
      print("esto permitira egregar numeros aleatorios a tus posibles claves")
      print("Y = si N = no")
      print("")
      print(b+"despues de esto tendras tu diccionario")
      print("Pero ahora para agregarlo a tu herramienta de fuerza bruta tendras que ir")
      print("ala ruta de la herramienta de fuerza bruta,y como se la ruta?")
      print("es facil lo primero que debes aser es abrir otra sesion y dirigirte ala")
      print("herramienta, una vez dentro de la herramienta pondras ")
      print("$ "+v+"pwd"+b)
      print("esto te dará la ruta de la carpeta, Despues regresas ala carpeta de la")
      print("herramienta de cupp y $ ls para ver el diccionario.txt y despues ")
      print("pondras este comando:")
      print("$ "+v+"mv -r "+ro+"Aki ira el nombre del diccionario  aki ira la ruta que copiaste"+b)
      print("ejemplo:")
      print("$ "+v+"mv -r "+ro+"jose.txt /data/data/com.termux/files/home"+b)
      print("Esto ara que se mueva el diccionario ala carpeta de la herramienta")
      print("de fuerza bruta ahora si puedes iniciar la fuerza bruta"+Reset)
      print("")
    
def uso_gemail():
       print(ro+"> "+a+"GUIA"+b)
       print("")
       print("Bueno Primero para el uso de esta herramienta tienes que crear un")
       print("diccionario como creo un diccionario? para crear un diccionario puedes")
       print("ir al menu principal y seleccionar el numero 2 y ir al apartado del")
       print("diccionario ai te explico como crear un diccionario con la")
       print("herramienta cupp")
       print("")
       print("Una vez creador el diccionario, y estando dentro de la herramienta")
       print("nos aparecera el menu al cual le vamos a dar al numero 2 ")
       print("una vez dado nos pedira el nombre del diccionario, escribimos el")
       print("nombre del diccionario y le demos enter, una vez dado enter,nos ")
       print("pedirá el correo de gmail cuando pongamos el usuario osea el")
       print("correo de gmail la herramienta comenzará aser su trabajo y a ")
       print("probar las posibles claves cusndo la encuentre se va a detener ")
       print("y asi se usa esta herramienta"+Reset)
       print("")
def uso_hammer():
       print(ro+"> "+a+"GUIA"+b)
       print("")
       print("Para utilizar esta herramienta tendras que buscar la ip")
       print("de la pagina a cual la vas a atacar ,Como obtengo la ip?")
       print("")
       print("facil para obtener la ip tienes que copiar el nombre de la")
       print("pagina por ejemplo:  "+v+"www.Portafolio.com  "+b+",no hay que poner")
       print("nada de "+r+"http:// "+b+"no nada de eso solo como esta en el ")
       print("ejemplo una vez obtenido el nombre abriremos otra ")
       print("sesion en termux donde pondremos el siguien comando")
       print("$ "+v+"ping "+b+"(aqui el nombre de la pagina) ejemplo:")
       print("$ "+v+"ping www.Portafolio.com"+b)
       print("")
       print("al dar enter te aparecera unos numero entre parentesis")
       print("esos de hay es la ip de la pagina,Una vez obtenido la ip")
       print("comenzaremos a realizar el ataque para eso pondremos")
       print("$ "+v+"python3 hammer.py "+b+", seguido de eso pondremos la"+v)
       print("-s "+b+"y la ip de la pagina ,despues pondremos el "+v+"-p "+b+"y el ")
       print("puerto por defecto es el puerto 80 ,seguido el "+v+"-t "+b+"por")
       print("defecto será el 135 ejemplo:")
       print("$ "+v+"python3 hammer.py -s "+ro+"209.159.222.36 "+v+"-p "+ro+"80 "+v+"-t "+ro+"135"+b)
       print("y asi es como realizamos el ataque DdoS con la ayuda")
       print("de la herramienta hammer.")
       print("")
       print(c+"["+b+"Ojo estos ataques Ddos servira depende de la pagina,")
       print("si la pagina es segura nesecitaras mas ayuda osea")
       print("mas telefonos o computadoras asiendo el ataque a la")
       print("dichosa pagina para asi poderla tumbar"+c+"]."+Reset)
       print("")
def uso_fbi():
       print(ro+"> "+a+"GUIA"+b)
       print("bueno esto sera un poco complicado asi que vamos al grano")
       print("una vez dentro de fbi te va a dar unas opciones")
       print("")
       print("nosotros escribiremos $ "+r+"token "+b+", despues no pedirá el")
       print("correo y la contraseña de tu facebook, una vez puesto ")
       print("el correo y la contraseña se saldrá de la herramienta")
       print("asique tenemos que volver a entrar ala herramienta, una")
       print("vez dentro pondremos el comando $ "+r+"help "+b+",help te dara")
       print("a conocer los comandos que la herramienta tiene, ")
       print("ahora te dare a conocer el funcionamiento de cada")
       print("comando:")
       print("")
       print(ro+"> "+a+"get_data "+r+"= "+b+"este comando te dará el numero de ")
       print("amigos que tienes en el facebook.")
       print("")
       print(ro+"> "+a+"get_info "+r+"= "+b+"este comando te dara informacion de una")
       print("amigo en especifico, una vez puesto este comando")
       print("tendras que entrar al perfil de tu amigo y copiar")
       print("la url de su perfil , despues copiada la url pegaras")
       print("en la herramienta y te dara informacion de el.")
       print("")
       print(ro+"> "+a+"dump_phone "+r+"= "+b+"este comando nos dará los numeros")
       print("de tus amigos nada del otro mundo")
       print("")
       print(ro+"> "+a+"dump_mail "+r+"= "+b+"con este comando nos dará los correos")
       print("de tus amigos")
       print("")
       print("bueno estas son las opciones mas importantes de esta")
       print("herramienta , y bueno asi se recolecta informacion."+Reset)
       print("")
def uso_wishfish():
       print(v+"GUIA"+b)
       print("Bueno para utilizar esta herramienta,Una vez estando dentro de la")
       print("herramienta nos saldra dos opciones"+a)
       print("Server.net")
       print('Ngrok'+b)
       print('Aqui tenemos dos opciones lo mas comun es poner la opcion 02,porque')
       print('Ngrok es la vieja confiable,bueno una vez puesto ya sea el 01 o el')
       print('02 comenzara a descargarse ya sea serveo.net o Ngrok.')
       print('Despues tendremos que salir de la herramienta aplastando Ctrl + c')
       print('Volvemos a entran con bash wishfish.sh.')
       print('Una vez dentro escogemos otra vez la opcion escogida antes')
       print('Despues nos dara el link .nrok.Este link .ngrok tendremos que mandar')
       print('ala victima o a ti.')
       print('Para aser funcionar la herramienta la victima o tu tienen que entrar al')
       print("link.Despues te saldra una ventanita donde pondras lo que sea y despues")
       print("te pedirá permitir camara la victima obviamente tendras que engañarla")
       print("para que le de a permitir.")
       print("Rapidamente tomará las fotos astas que pares presionando Ctrl + c")
       print('Una vez Tomada las Fotos se guardaran en la')
       print('herramienta y como las puedo ver?')
       print('para ver las fotos devemos que mover la foto ya sea a documentos o a cualquier')
       print('carpeta,y dar ls para poder ver el nombre de la foto guardada,para mover')
       print('tendras que poner estos comandos'+v)
       print('> '+b+'$ mv'+v+' aqui el nombre de la foto guardada   aqui la ruta de la carpeta '+b)
       print('EJEMPLO')
       print('$ mv cam26Mar2020120624.png /sdcard/Documents')
       print('En este caso se me movera en la carpeta Documentos.Ya solo falta entrar en ')
       print("la carpeta y ver que fotos a tomado")
       print("")
def uso_papaviruz():
       print(v+'GUIA'+b)
       print("Bueno aqui te enseñaré a crear el viruz,Lo primero que hay que ase es entrar")
       print('ala herramienta,una vez dentro seleccionamos si quieremos viruz para android')
       print(',Windowns,Una vez seleccionado la opcion ya sea 01 o 02 nos dará una lista')
       print('de viruz en formato .apk seleccionaremos cualquiera'+v)
       print("")
       print('['+b+'Ojo algunas de estos viruz dan error al guardar'+v+']'+b)
       print("")
       print('Cuando hallamos elejido nuestra apk,Tendremos que poner la ruta a que carpeta')
       print('enviaremos el viruz,para eso puedes abrir otra session en termux y llegar')
       print('asta la carperta y poner el comando'+v)
       print('> '+b+'$ pwd')
       print('este comando nos dara la ruta en la que estamos,copiaremos esa ruta y ')
       print('pegaremos en la herramienta y daremos enter')
       print('Despues solo debemos ir a esa carpeta donde hemos guardado el viruz.')
def uso_koroni():
       print(v+'GUIA'+b)
       print('Una vez estando dentro de la herramienta nos saldra 3 opciones'+a)
       print('')
       print('> '+b+'local.run'+r+' = '+b+'Con esta opcion solo pdremos mandar el link')
       print('a personas estando en nuestra red local'+a)
       print('')
       print('> '+b+'Serveo'+r+' = '+b+'Con esta opcion si podremos enviar el link fuera')
       print('de nuestra red local'+a)
       print('')
       print("> "+b+'Ngrok'+r+' = '+b+'Esta es igual que con la opcion serveo,este servidor es el')
       print('mas usado')
       print('')
       print('Una vez ya elejido el servidor ahora nos aparecera 5 opciones mas:'+a)
       print('')
       print('> '+b+'Mostrar Titulo'+r+' = '+b+'Aqui podemos poner un titulo al pishing'+a)
       print('')
       print('> '+b+'Mostrar Imagen'+r+' = '+b+'Aqui pondremos la ruta de la foto .jpg ejemplo:')
       print('$ /sdcard/Download/imagen.jpg'+a)
       print('')
       print('> '+b+'Mostrar Descripcion'+r+' = '+b+'Aqui podemos poner una mini descripcion'+a)
       print('')
       print('> '+b+'Mostrar Mini Url'+r+' = '+b+'Esto es para que sea mas creible puedes poner')
       print('una url falsa'+a)
       print('')
       print('> '+b+'Redireccionar'+r+' = '+b+'Aqui podemos redireccionar ala victima una vez que')
       print('entre al link,puedes poner cualquier url,obviamente valida ya sea facebook ')
       print('o cualquier pagina')
       print("")
       print('Despues que hallamos llenado todas la opciones o la mayoria,para generar el')
       print('link debemos escribir run,hay nos dara dos links,1 para enviar normalmente,')
       print('2 para enviar por facebook,Son diferentes ')
       print('Y asi se obtiene la ubicacion de cualquer persona,claro si asientas una buena')
       print('base de pishing con ingeneria social.')
       print("")
def uso_tbomb():
       print(v+'GUIA'+b)
       print('Al iniciar la herramienta tenemos que presionar la tecla enter,ai nos dara')
       print('5 opciones,Bueno la que nos interesa es la primera y la segunda.Una vez')
       print('escojida la primera opcion nos aparecera una opcion que nos pedirá el codigo')
       print('postal de tu pais.Si no sabes el codigo postal de tu pais solo buscas en ')
       print('en google el codigo de tu pais.Al escribir el codigo postal debes poner sin')
       print('el signo mas +,Despues puesto el codigo postal de tu pais sin el signo mas')
       print('debemos poner el numero de la victima,claro sin el codigo postal.Despues ')
       print('tendremos que poner el numero de mensajes que enviaremos a la victima, ')
       print('tendremos que poner el numero de sgundos que quieres que se envien los')
       print('mensajes')
       print("")
       print('Y asi se ase spam de mensajes con tbomb')
       print('')
